### PR TITLE
Clean up & attaching commercial license for the CLI

### PR DESCRIPTION
**Pull request by olofwalker**
References
-

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @olofwalker,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
@olofwalker, are we ready to merge this? 

I think that once merge it becomes immediately available. Anyway, I let you decide when to merge.

**Comment by olofwalker** [comment]
I suspect that this will do little harm, I mostly want to check if the license flag works

**Pull request merged**
